"use client";
import { ArrowRight, AudioLines, BrainCircuit, Image as ImageIcon, MapPin, MoreHorizontal, TrendingUp, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";
import { getSession, type SessionUser } from "@/lib/auth-session";
import { getDashboard, type DashboardData } from "@/lib/api";

const tones = ["bg-[#e3efec] text-[#2d7c78]", "bg-[#eaf2fa] text-[#427cac]", "bg-[#fff5dd] text-[#a77b21]", "bg-[#f2edfb] text-[#7657ae]"];

export function DashboardOverview() {
  const router = useRouter();
  const [user, setUser] = useState<SessionUser | null>(null);
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [chooseDetection, setChooseDetection] = useState(false);
  useEffect(() => {
    const session = getSession(); setUser(session);
    if (session?.token) getDashboard(session.token).then(setDashboard).catch(() => setDashboard(null));
  }, []);
  const firstName = user?.name.split(" ")[0] ?? "";
  const metrics = dashboard ? [
    ["Total species", dashboard.total_species], ["Population observed", dashboard.total_population],
    ["Images processed", dashboard.images_processed], ["Audio recordings", dashboard.audio_recordings],
  ] : [];
  const maxActivity = Math.max(...(dashboard?.population_activity.map(item => item.population) ?? [1]), 1);
  return <DashboardShell><div className="mx-auto max-w-[1440px] p-5 sm:p-8">
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm text-[#66796d]">Wildlife Population Intelligence System</p><h1 className="mt-1 text-3xl font-extrabold ui-page-title tracking-[-.045em]">{firstName ? `Good morning, ${firstName}.` : "Welcome."}</h1><p className="mt-2 text-sm text-[#6d756f]">Here’s what’s happening across your monitoring locations.</p></div><button onClick={() => setChooseDetection(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#263746] px-4 py-3 text-sm font-semibold text-white"><ImageIcon size={16}/> New detection</button></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value], index) => <article key={label as string} className="rounded-2xl border border-[#d8ddd7] bg-[#fffdf8] p-5"><div className={`grid h-10 w-10 place-items-center rounded-xl ${tones[index]}`}><TrendingUp size={19}/></div><p className="mt-6 text-sm text-[#6d756f]">{label}</p><p className="mt-1 text-3xl font-extrabold ui-page-title tracking-tight">{value as number}</p><p className="mt-3 text-xs font-semibold text-[#9a6b3f]">Live database total</p></article>)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-[#d8ddd7] bg-[#fffdf8]"><div className="flex items-center justify-between p-6"><div><h2 className="font-semibold">Population activity</h2><p className="mt-1 text-sm text-[#6d756f]">Verified observations from the database</p></div><MoreHorizontal size={19} className="text-[#6d756f]"/></div><div className="px-6 pb-6"><div className="relative flex h-56 items-end gap-3 overflow-hidden rounded-xl border-b border-[#d8ddd7] bg-[repeating-linear-gradient(to_bottom,#edf3ee_0,#edf3ee_1px,transparent_1px,transparent_25%)] px-3 pt-4">{dashboard?.population_activity.slice(-12).length ? dashboard.population_activity.slice(-12).map((item, index, items) => <div key={item.month} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-1"><span className="text-[10px] font-bold text-[#2d7c78] opacity-0 transition group-hover:opacity-100">{item.population}</span><span className={`w-full max-w-12 rounded-t-lg bg-gradient-to-t ${index === items.length - 1 ? "from-[#2d7c78] to-[#83b9ad]" : "from-[#a7d2bd] to-[#d8eadb]"} transition-all group-hover:from-[#23645f]`} style={{height: `${Math.max(18, Math.round(item.population / maxActivity * 150))}px`}} title={`${item.month}: ${item.population}`}/><span className="max-w-14 truncate text-[9px] text-[#6d756f]">{item.month.slice(0, 7)}</span></div>) : <p className="m-auto text-sm text-[#6d756f]">No population observations yet.</p>}</div></div></div><aside className="rounded-2xl bg-[#263746] p-6 text-white"><div className="flex items-center gap-2 text-[#d7c29a]"><BrainCircuit size={19}/><p className="text-xs font-bold uppercase tracking-[.15em]">Rule-based insight</p></div><p className="mt-6 text-xl font-bold tracking-tight">{dashboard?.ai_insight ?? "Loading database insight…"}</p><button onClick={() => router.push("/dashboard/insights")} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#d7c29a]">View population analysis <ArrowRight size={16}/></button></aside></section>
    <section className="mt-6 rounded-2xl border border-[#d8ddd7] bg-[#fffdf8]"><div className="flex items-center justify-between p-6"><div><h2 className="font-semibold">Recent detections</h2><p className="mt-1 text-sm text-[#6d756f]">Latest AI-assisted observations awaiting review.</p></div></div><div className="divide-y divide-[#e9efea]">{dashboard?.recent_detections.map(item => <article key={`${item.type}-${item.id}`} className="flex items-center gap-4 px-6 py-4"><div className="grid h-10 w-10 place-items-center rounded-xl ui-image-frame text-[#2d7c78]">{item.type === "audio" ? <AudioLines size={19}/> : <ImageIcon size={19}/>}</div><div className="min-w-0 flex-1"><p className="font-semibold">{item.species}</p><p className="mt-1 flex items-center gap-1 text-xs text-[#6d756f]"><MapPin size={12}/>{item.location ?? "Location not supplied"}</p></div><div className="hidden text-right sm:block"><p className="text-sm font-semibold text-[#277047]">{item.confidence ? `${Math.round(item.confidence * 100)}%` : "—"}</p></div><span className="rounded-lg bg-[#f0f6f1] px-2.5 py-1 text-xs font-semibold text-[#3d7250]">{item.count} observed</span></article>)}</div></section>
    {chooseDetection && <div className="fixed inset-0 z-40 grid place-items-center bg-[#263746]/30 p-5"><div className="w-full max-w-md rounded-2xl bg-[#fffdf8] p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2d7c78]">New detection</p><h2 className="mt-2 text-xl font-bold">What would you like to analyze?</h2></div><button onClick={() => setChooseDetection(false)} aria-label="Close"><X size={18}/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={() => router.push("/dashboard/image-detection")} className="rounded-2xl border border-[#d8ddd7] p-5 text-left hover:border-[#2d7c78] hover:bg-[#f5faf6]"><ImageIcon size={22} className="text-[#2d7c78]"/><p className="mt-4 font-semibold">Image</p><p className="mt-1 text-sm text-[#6d756f]">Upload a camera-trap photo.</p></button><button onClick={() => router.push("/dashboard/audio-detection")} className="rounded-2xl border border-[#d8ddd7] p-5 text-left hover:border-[#2d7c78] hover:bg-[#f5faf6]"><AudioLines size={22} className="text-[#2d7c78]"/><p className="mt-4 font-semibold">Audio</p><p className="mt-1 text-sm text-[#6d756f]">Upload a field recording.</p></button></div></div></div>}
  </div></DashboardShell>;
}
