"use client";
import { useEffect, useState } from "react";
import { BarChart3, Download, FileText, Leaf, RefreshCw, Trash2, Plus, X } from "lucide-react";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";
import { DataCard } from "@/components/shared/DataCard";
import { PageContainer } from "@/components/shared/PageContainer";
import { PageHeader } from "@/components/shared/Pageheader";
import { Button } from "@/components/ui/button";
import { getSession } from "@/lib/auth-session";
import { getDashboard, getAnalyticsPopulation, getAnalyticsSpecies, getPopulationSummary, getReports, generateReport, deleteReport, createReport, downloadReport, type Report } from "@/lib/api";

export function InsightsPage(){
 const [dashboard,setDashboard]=useState<any>(null); const [trend,setTrend]=useState<Array<{month:string;population:number}>>([]); const [species,setSpecies]=useState<Array<{species:string;image_detections:number;audio_detections:number}>>([]); const [population,setPopulation]=useState<any>(null); const [reports,setReports]=useState<Report[]>([]); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<number|null>(null); const [showForm,setShowForm]=useState(false); const [reportName,setReportName]=useState(""); const [reportType,setReportType]=useState("population");
 const load=()=>{const token=getSession()?.token;if(!token)return; Promise.all([getDashboard(token),getAnalyticsPopulation(token),getAnalyticsSpecies(token),getPopulationSummary(token),getReports(token)]).then(([d,t,s,p,r])=>{setDashboard(d);setTrend(t.population_trends);setSpecies(s.species_distribution);setPopulation(p);setReports(r)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load insights."))}; useEffect(load,[]);
 const token= getSession()?.token; const normalizedTrend=trend.map(item=>({...item,population:Number(item.population)||0})); const max=Math.max(...normalizedTrend.map(x=>x.population),1); const detections=species.reduce((n,x)=>n+x.image_detections+x.audio_detections,0);
 const run=async(id:number)=>{if(!token)return;setBusy(id);try{await generateReport(id,token);load()}finally{setBusy(null)}}; const remove=async(id:number)=>{if(!token)return;await deleteReport(id,token);load()};
 const download=async(report:Report)=>{if(!token)return;try{await downloadReport(report.id,token,report.name)}catch(c){setError(c instanceof Error?c.message:"Unable to download report.")}}; const create=async(e:React.FormEvent)=>{e.preventDefault();if(!token||!reportName.trim())return;setBusy(-1);try{await createReport({name:reportName.trim(),report_type:reportType},token);setReportName("");setShowForm(false);load()}finally{setBusy(null)}};
 return <DashboardShell><PageContainer><PageHeader breadcrumb="Dashboard / Insights" title="Population insights" description="Understand wildlife detections, population observations, trends, and reports from your database."><Button variant="secondary" onClick={load}><RefreshCw size={16}/>Refresh data</Button></PageHeader>{error&&<p className="mt-5 rounded-xl bg-[#fff1ed] p-3 text-sm text-[#a4493b]">{error}</p>}
 <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Total detections",detections],["Species detected",species.length],["Population observed",population?.total_population??0],["Observations",population?.recent_observations?.length??0],["Reports generated",reports.filter(r=>r.status==="Generated").length]].map(([label,value])=><DataCard key={label as string} className="p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.08em] text-[#6d756f]">{label}</p><BarChart3 size={17} className="text-[#2d7c78]"/></div><p className="mt-4 text-3xl font-extrabold ui-page-title">{value as number}</p><p className="mt-2 text-xs font-semibold text-[#9a6b3f]">Live database value</p></DataCard>)}</section>
 <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><DataCard className="p-6"><div className="flex items-start justify-between"><div><p className="ui-kicker">Population activity</p><h2 className="mt-2 text-xl font-bold">Observed trend</h2><p className="mt-1 text-sm text-[#6d756f]">Monthly totals from saved population records.</p></div><Leaf className="text-[#2d7c78]" size={22}/></div>{normalizedTrend.length?<div className="mt-8 flex h-64 items-end gap-2 border-b border-[#d8ddd7] pb-1">{normalizedTrend.map(item=><div key={item.month} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-[11px] font-bold text-[#2d7c78]">{item.population}</span><span className="w-full rounded-t-lg bg-gradient-to-t from-[#2d7c78] to-[#8dbdb0] transition-all group-hover:from-[#23645f]" style={{height:`${Math.max(18, Math.round(item.population / max * 150))}px`}} title={`${item.month}: ${item.population}`}/><span className="max-w-16 truncate text-[10px] text-[#6d756f]">{item.month.slice(0,7)}</span></div>)}</div>:<div className="mt-8 grid min-h-56 place-items-center rounded-2xl bg-[#e8f0ea] text-center text-sm text-[#6d756f]">More saved observations are needed to show a trend.</div>}</DataCard><DataCard className="p-6"><p className="ui-kicker">Species insights</p><h2 className="mt-2 text-xl font-bold">Top recorded species</h2><div className="mt-5 space-y-3">{species.slice().sort((a,b)=>b.image_detections+b.audio_detections-(a.image_detections+a.audio_detections)).slice(0,6).map((row,i)=><div key={row.species} className="flex items-center gap-3 rounded-xl bg-[#eef3ee] p-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#d6e9df] text-xs font-extrabold text-[#2d7c78]">{i+1}</span><span className="min-w-0 flex-1 truncate text-sm font-bold">{row.species}</span><span className="text-sm font-extrabold">{row.image_detections+row.audio_detections}</span></div>)}{!species.length&&<p className="py-8 text-sm text-[#6d756f]">No detections yet.</p>}</div></DataCard></section>
 <DataCard className="mt-6 overflow-hidden"><div className="p-6"><p className="ui-kicker">Detection breakdown</p><h2 className="mt-2 text-xl font-bold">Analytics by species</h2></div><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-[#eef3ee] text-xs uppercase text-[#6d756f]"><tr><th className="px-6 py-4">Species</th><th className="px-6 py-4">Image detections</th><th className="px-6 py-4">Audio detections</th><th className="px-6 py-4">Total</th></tr></thead><tbody>{species.map(row=><tr key={row.species} className="border-t border-[#e1e6e1]"><td className="px-6 py-4 font-bold">{row.species}</td><td className="px-6 py-4">{row.image_detections}</td><td className="px-6 py-4">{row.audio_detections}</td><td className="px-6 py-4 font-extrabold text-[#2d7c78]">{row.image_detections+row.audio_detections}</td></tr>)}</tbody></table></div></DataCard>
 <DataCard className="mt-6 overflow-hidden"><div className="flex items-center justify-between p-6"><div><p className="ui-kicker">Research exports</p><h2 className="mt-2 text-xl font-bold">Report history</h2><p className="mt-1 text-sm text-[#6d756f]">Generate and download reports from current database records.</p></div><div className="flex items-center gap-3"><FileText className="text-[#9a6b3f]"/><Button onClick={()=>setShowForm(true)}><Plus size={16}/>Create report</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="bg-[#eef3ee] text-xs uppercase text-[#6d756f]"><tr><th className="px-6 py-4">Report</th><th className="px-6 py-4">Category</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Actions</th></tr></thead><tbody>{reports.map(report=><tr key={report.id} className="border-t border-[#e1e6e1]"><td className="px-6 py-4 font-bold">{report.name}</td><td className="px-6 py-4 capitalize">{report.report_type}</td><td className="px-6 py-4"><span className="rounded-full bg-[#e3efec] px-2.5 py-1 text-xs font-bold text-[#2d7c78]">{report.status}</span></td><td className="px-6 py-4"><div className="flex gap-2"><Button className="px-3 py-2 text-xs" onClick={()=>run(report.id)} disabled={busy===report.id}>{busy===report.id?"Working…":"Generate"}</Button><a className="inline-flex items-center gap-1 rounded-full border border-[#d8ddd7] px-3 py-2 text-xs font-bold" href="#" onClick={event=>{event.preventDefault();download(report)}}><Download size={13}/>Download</a><button onClick={()=>remove(report.id)} className="rounded-lg p-2 text-[#a4493b] hover:bg-[#fff1ed]"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{!reports.length&&<p className="p-8 text-center text-sm text-[#6d756f]">No reports yet.</p>}</div></DataCard>
 {showForm&&<div className="fixed inset-0 z-40 grid place-items-center bg-[#263746]/40 p-5"><form onSubmit={create} className="w-full max-w-lg rounded-3xl border border-[#d8ddd7] bg-[#fffdf8] p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="ui-kicker">Database export</p><h2 className="mt-2 text-xl font-bold">Create report</h2><p className="mt-1 text-sm text-[#6d756f]">Save a report definition from your live database.</p></div><button type="button" onClick={()=>setShowForm(false)} aria-label="Close"><X size={18}/></button></div><label className="mt-6 block text-sm font-bold">Report name<input required value={reportName} onChange={e=>setReportName(e.target.value)} placeholder="August population summary" className="mt-2 w-full rounded-xl border border-[#d8ddd7] bg-[#fffdf8] px-3 py-2.5 text-sm"/></label><label className="mt-4 block text-sm font-bold">Category<select value={reportType} onChange={e=>setReportType(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d8ddd7] bg-[#fffdf8] px-3 py-2.5 text-sm"><option value="population">Population</option><option value="detection">Detection</option><option value="species">Species</option></select></label><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={()=>setShowForm(false)}>Cancel</Button><Button type="submit" disabled={busy===-1}>{busy===-1?"Creating…":"Create report"}</Button></div></form></div>} </PageContainer></DashboardShell>
}
