"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, EyeOff, LoaderCircle, Mail, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { saveSession, type UserRole } from "@/lib/auth-session";
import { login, registerAccount } from "@/lib/api";
type Mode="login"|"register"|"forgot"; type Role=UserRole; type Values={name?:string;email:string;password?:string;role?:Role};
const schemas={login:z.object({email:z.string().email("Enter a valid work email."),password:z.string().min(1,"Enter your password.")}),register:z.object({name:z.string().min(2,"Please enter your name."),email:z.string().email("Enter a valid work email."),role:z.enum(["admin","researcher","forest_officer"],{message:"Choose your role."}),password:z.string().min(8,"Use at least 8 characters.")}),forgot:z.object({email:z.string().email("Enter a valid work email.")})};
const copy={login:["Welcome back","Sign in to continue protecting what matters.","Sign in"],register:["Join your field team","Create your Wildlife Population Intelligence System account.","Create account"],forgot:["Reset your password","We’ll send a secure reset link to your work email.","Send reset link"]} as const;
export function AuthForm({mode}:{mode:Mode}){const[show,setShow]=useState(false);const[done,setDone]=useState(false);const[apiError,setApiError]=useState<string|null>(null);const{register,handleSubmit,watch,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schemas[mode]),mode:"onTouched"});const password=watch("password")??"";const strength=[password.length>=8,/[A-Z]/.test(password),/[0-9]/.test(password)].filter(Boolean).length;const[title,text,action]=copy[mode];const submit=async(values:Values)=>{try{setApiError(null);if(mode==="login"){const result=await login(values.email,values.password!);saveSession({...result.user,token:result.access_token});}else if(mode==="register"){await registerAccount({name:values.name!,email:values.email,password:values.password!,role:values.role!});}setDone(true)}catch(error){setApiError(error instanceof Error?error.message:"Unable to continue.")}};
if(done)return <div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e7f3e9] text-[#277047]"><Mail size={21}/></div><h2 className="mt-7 text-3xl font-extrabold ui-page-title tracking-[-.045em] text-[#263746]">{mode==="forgot"?"Check your inbox":"You’re all set."}</h2><p className="mt-3 leading-7 text-[#68786e]">{mode==="forgot"?"If an account exists for that email, you’ll receive a password reset link shortly.":"Your Wildlife Population Intelligence System account is ready. Continue to your workspace."}</p><Link href={mode==="forgot"?"/login":"/dashboard"} className="mt-8 inline-block text-sm font-semibold text-[#2d7c78]">{mode==="forgot"?"Back to sign in":"Continue to dashboard →"}</Link></div>;
return <><Link href="/" className="mb-10 inline-block text-sm font-semibold text-[#628075]">← Back to site</Link><p className="text-xs font-bold uppercase tracking-[.16em] text-[#2d7c78]">Secure workspace access</p><h2 className="mt-3 text-3xl font-extrabold ui-page-title tracking-[-.045em] text-[#263746]">{title}</h2><p className="mt-3 leading-7 text-[#68786e]">{text}</p><form onSubmit={handleSubmit(submit)} className="mt-8 space-y-5">{mode==="register"&&<><Field label="Full name" error={errors.name?.message}><input placeholder="Dr. Maya Rao" {...register("name")}/></Field><Field label="Your role" error={errors.role?.message}><select defaultValue="" {...register("role")}><option value="" disabled>Select the work you do</option><option value="admin">Administrator — manage people & access</option><option value="researcher">Researcher — analyze data & reports</option><option value="forest_officer">Forest Officer — monitor field detections</option></select></Field></>}<Field label="Work email" error={errors.email?.message}><input autoComplete="email" placeholder="you@organization.org" {...register("email")}/></Field>{mode!=="forgot"&&<Field label="Password" error={errors.password?.message}><div className="relative"><input type={show?"text":"password"} className="pr-12" placeholder="••••••••" {...register("password")}/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3 text-[#789084]">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></Field>}{apiError&&<p className="text-sm font-medium text-[#bd5656]">{apiError}</p>}{mode==="register"&&<><div className="flex gap-1.5">{[1,2,3].map(n=><span key={n} className={`h-1 flex-1 rounded-full ${n<=strength?"bg-[#4d9a68]":"bg-[#e3ece5]"}`}/>)}</div><p className="-mt-3 text-xs text-[#75857b]">Use 8+ characters, a capital letter, and a number.</p></>}<Button type="submit" className="w-full" arrow disabled={isSubmitting}>{isSubmitting?<><LoaderCircle size={16} className="animate-spin"/> Working…</>:action}</Button></form><p className="mt-8 border-t border-[#e5ece7] pt-6 text-sm text-[#708077]">{mode==="login"?<>New to Wildlife Population Intelligence System? <Link href="/register" className="font-semibold text-[#2d7c78]">Create an account</Link></>:mode==="register"?<>Already have access? <Link href="/login" className="font-semibold text-[#2d7c78]">Sign in</Link></>:null}</p><div className="mt-8 flex items-center gap-2 text-xs text-[#819087]"><ShieldCheck size={15} className="text-[#5b956e]"/> Protected with enterprise-grade security</div></>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-[#29483b]">{label}</span><div className="[&_input]:h-12 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-[#d9e4dd] [&_input]:px-3.5 [&_input]:text-sm [&_input]:outline-none [&_input:focus]:border-[#43855d] [&_input:focus]:ring-4 [&_input:focus]:ring-[#dfeee3] [&_select]:h-12 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-[#d9e4dd] [&_select]:bg-[#fffdf8] [&_select]:px-3.5 [&_select]:text-sm">{children}</div>{error&&<p className="mt-1.5 text-xs font-medium text-[#bd5656]">{error}</p>}</label>}
