"use client";
import { useCallback, useEffect, useState } from "react";
import { Users } from "lucide-react";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";
import { getUsers, type ApiUser } from "@/lib/api";
import { getSession, roleLabel } from "@/lib/auth-session";
import { DataCard } from "@/components/shared/DataCard";
import { PageContainer } from "@/components/shared/PageContainer";
import { PageHeader } from "@/components/shared/Pageheader";
export function UsersPage(){const[users,setUsers]=useState<ApiUser[]>([]);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(true);const load=useCallback(async()=>{const token=getSession()?.token;if(!token)return;setLoading(true);setError(null);try{setUsers(await getUsers(token));}catch(firstError){try{await new Promise(resolve=>setTimeout(resolve,500));setUsers(await getUsers(token));}catch(secondError){setError(secondError instanceof Error?secondError.message:firstError instanceof Error?firstError.message:"Unable to load users.");}}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);return <DashboardShell><PageContainer><PageHeader breadcrumb="Dashboard / Users" title="Team members" description="Live account records. Administrator access is required."/>{error?<DataCard className="mt-8 flex items-center justify-between gap-4 p-6 text-sm text-[#bd5656]"><span>{error}</span><button onClick={()=>void load()} className="rounded-lg border border-[#e5b7b7] px-3 py-1.5 text-xs font-semibold">Retry</button></DataCard>:loading?<DataCard className="mt-8 p-6 text-sm text-[#6d756f]">Loading team members…</DataCard>:<><DataCard className="mt-8 p-5"><Users size={19} className="text-[#2d7c78]"/><p className="mt-4 text-sm text-[#6d756f]">Total users</p><p className="text-3xl font-extrabold ui-page-title">{users.length}</p></DataCard><DataCard className="mt-6 overflow-hidden"><table className="w-full text-left"><thead className="bg-[#eef3ee] text-xs uppercase text-[#7b8b81]"><tr><th className="px-6 py-4">Name</th><th className="px-6 py-4">Email</th><th className="px-6 py-4">Role</th><th className="px-6 py-4">Status</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-[#e9efea]"><td className="px-6 py-4 font-semibold">{user.name}</td><td className="px-6 py-4">{user.email}</td><td className="px-6 py-4">{roleLabel(user.role)}</td><td className="px-6 py-4">{user.is_active?"Active":"Inactive"}</td></tr>)}</tbody></table></DataCard></>}</PageContainer></DashboardShell>}
