"use client";

import { FormEvent, useEffect, useState } from "react";
import { Bird, Plus, Search, Trash2, X } from "lucide-react";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";
import { createSpecies, deleteSpecies, getSpecies, updateSpecies, type Species, type SpeciesInput } from "@/lib/api";
import { getSession } from "@/lib/auth-session";
import { Button } from "@/components/ui/button";
import { DataCard } from "@/components/shared/DataCard";
import { PageContainer } from "@/components/shared/PageContainer";
import { PageHeader } from "@/components/shared/Pageheader";

const emptyForm: SpeciesInput = { common_name: "", scientific_name: "", species_group: "", iucn_status: "", description: "", habitat: "", diet: "" };

export function SpeciesPage() {
  const [items, setItems] = useState<Species[]>([]); const [selected, setSelected] = useState<Species | null>(null); const [editing, setEditing] = useState<Species | null>(null); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async (term = query) => { const token = getSession()?.token; if (!token) return; try { setLoading(true); setError(null); setItems(await getSpecies(token, term)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load species."); } finally { setLoading(false); } };
  useEffect(() => { const search = new URLSearchParams(window.location.search).get("search") ?? ""; setQuery(search); load(search); }, []);
  const remove = async (item: Species) => { if (!confirm(`Delete ${item.common_name}?`)) return; const token = getSession()?.token; if (!token) return; try { await deleteSpecies(item.id, token); if (selected?.id === item.id) setSelected(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete species."); } };
  return <DashboardShell><PageContainer><PageHeader breadcrumb="Dashboard / Species catalogue" title="Species catalogue" description="Browse and manage biodiversity records stored in your database."><div className="flex flex-wrap gap-2"><form onSubmit={event => { event.preventDefault(); load(); }} className="relative"><Search size={16} className="absolute left-3 top-3 text-[#77838a]" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search species…" className="h-10 w-60 rounded-xl border border-[#d8ddd7] bg-[#fffdf8] pl-9 pr-3 text-sm outline-none focus:border-[#2d7c78]" /></form><Button onClick={() => setEditing({ id: 0, ...emptyForm, created_at: "", updated_at: "" })}><Plus size={16} />Add species</Button></div></PageHeader>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Species records" value={items.length} /><Metric label="Conservation statuses" value={new Set(items.map(item => item.iucn_status)).size} /><Metric label="Species groups" value={new Set(items.map(item => item.species_group)).size} /></section>
    <DataCard className="mt-6 overflow-hidden"><div className="p-6"><h2 className="font-semibold">Biodiversity records</h2><p className="mt-1 text-sm text-[#6d756f]">Select a row to view or edit the full record.</p>{error && <p className="mt-3 text-sm text-[#bd5656]">{error}</p>}</div><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead className="border-y border-[#e1e6e1] bg-[#eef3ee] text-xs uppercase tracking-wide text-[#7b8b81]"><tr>{["Species", "Scientific name", "Group", "IUCN status", "Updated", ""].map(label => <th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-[#e9efea]">{loading ? <tr><td colSpan={6} className="px-5 py-10 text-center text-sm text-[#6d756f]">Loading records…</td></tr> : items.length ? items.map(item => <tr key={item.id} onClick={() => setSelected(item)} className="cursor-pointer hover:bg-[#f8fbf8]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl ui-image-frame text-[#2d7c78]"><Bird size={18} /></span><span className="font-semibold">{item.common_name}</span></div></td><td className="px-5 py-4 text-sm italic text-[#6d756f]">{item.scientific_name}</td><td className="px-5 py-4 text-sm">{item.species_group}</td><td className="px-5 py-4"><span className="rounded-full bg-[#fff3df] px-2.5 py-1 text-xs font-semibold text-[#9a7020]">{item.iucn_status}</span></td><td className="px-5 py-4 text-sm text-[#6d756f]">{new Date(item.updated_at).toLocaleDateString()}</td><td className="px-5 py-4"><button onClick={event => { event.stopPropagation(); remove(item); }} aria-label={`Delete ${item.common_name}`} className="rounded-lg p-2 text-[#a94343] hover:bg-[#fff2f2]"><Trash2 size={16} /></button></td></tr>) : <tr><td colSpan={6} className="px-5 py-10 text-center text-sm text-[#6d756f]">No species match this search.</td></tr>}</tbody></table></div></DataCard>
    {selected && <SpeciesDrawer item={selected} close={() => setSelected(null)} edit={() => { setEditing(selected); setSelected(null); }} remove={() => remove(selected)} />}{editing && <SpeciesForm item={editing} close={() => setEditing(null)} saved={() => { setEditing(null); load(); }} />}
  </PageContainer></DashboardShell>;
}

function Metric({ label, value }: { label: string; value: number }) { return <DataCard className="p-5"><Bird size={19} className="text-[#2d7c78]" /><p className="mt-5 text-sm text-[#6d756f]">{label}</p><p className="mt-1 text-3xl font-extrabold ui-page-title">{value}</p></DataCard>; }
function SpeciesDrawer({ item, close, edit, remove }: { item: Species; close: () => void; edit: () => void; remove: () => void }) { return <div className="fixed inset-0 z-30 bg-[#263746]/20 backdrop-blur-[1px]"><aside className="absolute right-0 top-0 h-full w-full max-w-md overflow-y-auto bg-[#fffdf8] p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2d7c78]">Species profile</p><h2 className="mt-2 text-2xl font-extrabold ui-page-title">{item.common_name}</h2><p className="mt-1 italic text-[#6d756f]">{item.scientific_name}</p></div><button onClick={close} aria-label="Close details"><X size={18} /></button></div><div className="mt-7 grid grid-cols-2 gap-3"><Info label="Conservation" value={item.iucn_status} /><Info label="Group" value={item.species_group} /><Info label="Habitat" value={item.habitat || "Not recorded"} /><Info label="Diet" value={item.diet || "Not recorded"} /></div><section className="mt-7"><h3 className="font-semibold">Description</h3><p className="mt-2 text-sm leading-6 text-[#68796f]">{item.description || "No description has been added."}</p></section><div className="mt-8 flex gap-3"><Button onClick={edit}>Edit record</Button><Button variant="secondary" onClick={remove}>Delete</Button></div></aside></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#f6f9f6] p-3"><p className="text-xs text-[#6d756f]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function SpeciesForm({ item, close, saved }: { item: Species; close: () => void; saved: () => void }) { const [form, setForm] = useState<SpeciesInput>({ common_name: item.common_name, scientific_name: item.scientific_name, species_group: item.species_group, iucn_status: item.iucn_status, description: item.description || "", habitat: item.habitat || "", diet: item.diet || "" }); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const change = (field: keyof SpeciesInput, value: string) => setForm(current => ({ ...current, [field]: value })); const submit = async (event: FormEvent) => { event.preventDefault(); const token = getSession()?.token; if (!token) return; try { setBusy(true); setError(null); if (item.id) await updateSpecies(item.id, form, token); else await createSpecies(form, token); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save species."); } finally { setBusy(false); } }; return <div className="fixed inset-0 z-40 grid place-items-center bg-[#263746]/30 p-5"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-[#fffdf8] p-7 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2d7c78]">Database record</p><h2 className="mt-2 text-xl font-bold">{item.id ? "Edit species" : "Add species"}</h2></div><button type="button" onClick={close} aria-label="Close form"><X size={18} /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{([['common_name','Common name'],['scientific_name','Scientific name'],['species_group','Species group'],['iucn_status','IUCN status'],['habitat','Habitat'],['diet','Diet']] as Array<[keyof SpeciesInput, string]>).map(([field,label]) => <label key={field} className="text-sm font-medium">{label}<input required={field === 'common_name' || field === 'scientific_name' || field === 'species_group' || field === 'iucn_status'} value={form[field] || ""} onChange={event => change(field, event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#d8ddd7] px-3 py-2.5 text-sm outline-none focus:border-[#2d7c78]" /></label>)}</div><label className="mt-4 block text-sm font-medium">Description<textarea value={form.description || ""} onChange={event => change("description", event.target.value)} rows={4} className="mt-1.5 w-full rounded-xl border border-[#d8ddd7] px-3 py-2.5 text-sm outline-none focus:border-[#2d7c78]" /></label>{error && <p className="mt-3 text-sm text-[#bd5656]">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save species"}</Button></div></form></div>; }
