"use client";
import { useEffect, useState } from "react";
import { BarChart3 } from "lucide-react";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";
import { getAnalyticsPopulation, getAnalyticsSpecies } from "@/lib/api";
import { getSession } from "@/lib/auth-session";
import { DataCard } from "@/components/shared/DataCard";
import { PageContainer } from "@/components/shared/PageContainer";
import { PageHeader } from "@/components/shared/Pageheader";
export function AnalyticsPage(){const[trend,setTrend]=useState<Array<{month:string;population:number}>>([]);const[species,setSpecies]=useState<Array<{species:string;image_detections:number;audio_detections:number}>>([]);const[error,setError]=useState<string|null>(null);useEffect(()=>{const token=getSession()?.token;if(token)Promise.all([getAnalyticsPopulation(token),getAnalyticsSpecies(token)]).then(([p,s])=>{setTrend(p.population_trends);setSpecies(s.species_distribution)}).catch(c=>setError(c instanceof Error?c.message:"Unable to load analytics."));},[]);const max=Math.max(...trend.map(x=>x.population),1);return <DashboardShell><PageContainer><PageHeader breadcrumb="Dashboard / Analytics" title="Population analytics" description="Live trends and detection totals from the database."/>{error&&<p className="mt-6 text-sm text-[#bd5656]">{error}</p>}<section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Months with data" value={trend.length}/><Metric label="Species detected" value={species.length}/><Metric label="Total detections" value={species.reduce((n,x)=>n+x.image_detections+x.audio_detections,0)}/></section><DataCard className="mt-6 p-6"><h2 className="font-semibold">Population trend</h2><p className="mt-1 text-sm text-[#6d756f]">Monthly population totals. Empty means no saved observations.</p><div className="mt-8 flex h-52 items-end gap-3 border-b border-[#e5ede7]">{trend.length?trend.map((item,index)=><span key={item.month} title={`${item.month}: ${item.population}`} className={`flex-1 rounded-t-md ${index>8?"bg-[#4a9363]":"bg-[#cce5d1]"}`} style={{height:`${Math.max(6,item.population/max*100)}%`}}/>):<p className="m-auto text-sm text-[#6d756f]">No population data yet.</p>}</div></DataCard><DataCard className="mt-6 overflow-hidden"><div className="p-6"><h2 className="font-semibold">Detection totals by species</h2></div><table className="w-full text-left"><thead className="bg-[#eef3ee] text-xs uppercase text-[#7b8b81]"><tr><th className="px-6 py-4">Species</th><th className="px-6 py-4">Image detections</th><th className="px-6 py-4">Audio detections</th></tr></thead><tbody>{species.length?species.map(row=><tr key={row.species} className="border-t border-[#e9efea]"><td className="px-6 py-4 font-semibold">{row.species}</td><td className="px-6 py-4">{row.image_detections}</td><td className="px-6 py-4">{row.audio_detections}</td></tr>):<tr><td colSpan={3} className="px-6 py-10 text-center text-sm text-[#6d756f]">No detections yet.</td></tr>}</tbody></table></DataCard></PageContainer></DashboardShell>};function Metric({label,value}:{label:string;value:number}){return <DataCard className="p-5"><BarChart3 size={19} className="text-[#2d7c78]"/><p className="mt-5 text-sm text-[#6d756f]">{label}</p><p className="mt-1 text-3xl font-extrabold ui-page-title">{value}</p></DataCard>}
