"use client";
import { useEffect, useRef, useState } from "react";
import { CheckCircle2, ImageIcon, ImagePlus, MapPin, PawPrint, ScanSearch, Upload, X } from "lucide-react";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";
import { Button } from "@/components/ui/button";
import { getSession } from "@/lib/auth-session";
import { getImages, uploadImage, API_URL, type Detection } from "@/lib/api";

export function ImageDetectionPage() {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [location, setLocation] = useState(""); const [rows, setRows] = useState<Detection[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = () => { const token = getSession()?.token; if (token) getImages(token).then(setRows).catch(() => setError("Unable to load recent detections.")); };
  useEffect(load, []);
  const submit = async () => { const token = getSession()?.token; if (!file || !token) return; try { setBusy(true); setError(null); await uploadImage(file, token, location || undefined); setFile(null); setLocation(""); load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Upload failed."); } finally { setBusy(false); } };
  const latest = rows[0]; const annotatedUrl = latest?.annotated_image_url ? new URL(latest.annotated_image_url, API_URL).toString() : null; const grouped = (row?: Detection) => { const map = new Map<string, number>(); (row?.detections ?? []).forEach(item => map.set(item.species.common_name, (map.get(item.species.common_name) ?? 0) + 1)); return [...map.entries()]; }; const stats: Array<[typeof ImageIcon, string, string | number]> = [[ImageIcon, "Images processed", rows.length], [PawPrint, "Species detected", new Set(rows.flatMap(item => (item.detections ?? []).map(d => d.species.common_name)).concat(rows.map(item => item.species?.common_name ?? "")).filter(Boolean)).size], [ScanSearch, "Animals counted", rows.reduce((total, item) => total + (item.animal_count ?? 0), 0)], [CheckCircle2, "Average confidence", rows.length ? `${Math.round(rows.reduce((total, item) => total + (item.confidence ?? 0), 0) / rows.length * 100)}%` : "—"]];
  return <DashboardShell><div className="mx-auto max-w-[1440px] p-5 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#6d756f]">Dashboard / Image detection</p><h1 className="mt-1 text-3xl font-extrabold ui-page-title tracking-[-.045em]">Image detection</h1><p className="mt-2 text-sm text-[#6d756f]">Analyze wildlife camera-trap images with AI-assisted species identification.</p></div><Button onClick={() => input.current?.click()} arrow><Upload size={16}/> Upload images</Button></div><input ref={input} onChange={event => setFile(event.target.files?.[0] ?? null)} accept="image/png,image/jpeg,image/webp" type="file" className="hidden"/>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([Icon, label, value], index) => { const CardIcon = Icon; return <article key={label} className="rounded-2xl border border-[#d8ddd7] bg-[#fffdf8] p-5"><div className={`grid h-10 w-10 place-items-center rounded-xl ${["bg-[#e3efec] text-[#2d7c78]","bg-[#eaf2fa] text-[#427cac]","bg-[#fff5dd] text-[#a77b21]","bg-[#f2edfb] text-[#7657ae]"][index]}`}><CardIcon size={19}/></div><p className="mt-6 text-sm text-[#6d756f]">{label}</p><p className="mt-1 text-3xl font-extrabold ui-page-title">{value}</p><p className="mt-3 text-xs font-semibold text-[#9a6b3f]">Live database total</p></article>})}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-[#d8ddd7] bg-[#fffdf8] p-6"><h2 className="font-semibold">Upload wildlife image</h2><p className="mt-1 text-sm text-[#6d756f]">Upload JPG, PNG, or WEBP images up to 50 MB.</p><button onClick={() => input.current?.click()} className="mt-6 flex min-h-72 w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#b8d8c0] bg-[#e4f0e9] px-5 text-center transition hover:border-[#2d7c78] hover:bg-[#dcece4]"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#dff0e3] text-[#2e7650]">{file ? <ImageIcon size={29}/> : <ImagePlus size={29}/>}</span><p className="mt-5 font-semibold">{file ? file.name : "Drop an image here"}</p><p className="mt-2 text-sm text-[#6d756f]">{file ? `${Math.ceil(file.size / 1024)} KB · ready for analysis` : "or select a file from your computer"}</p><span className="mt-5 text-sm font-semibold text-[#2e7650]">Browse files</span></button>{file && <div className="mt-4 flex items-center justify-between rounded-xl bg-[#e3efec] p-3 text-sm"><span className="flex items-center gap-2 text-[#356047]"><CheckCircle2 size={17}/> Ready for model analysis</span><button onClick={() => setFile(null)} className="text-[#6c8576]"><X size={17}/></button></div>}{error && <p className="mt-3 text-sm text-[#bd5656]">{error}</p>}<Button onClick={submit} disabled={!file || busy} className="mt-4 w-full">{busy ? "Processing…" : "Analyze image"}</Button></div><aside className="rounded-2xl border border-[#d8ddd7] bg-[#fffdf8] p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2d7c78]">Latest result</p><div className="mt-6 grid aspect-[4/3] place-items-center overflow-hidden rounded-2xl ui-image-frame text-[#2d7c78]">{annotatedUrl ? <img className="h-full w-full object-contain" src={annotatedUrl} alt="Annotated wildlife detection"/> : <PawPrint size={42}/>}</div><div className="mt-5"><h2 className="text-xl font-bold">{latest ? `${latest.animal_count ?? 0} animal${latest.animal_count === 1 ? "" : "s"} detected` : "Awaiting image"}</h2><p className="mt-1 text-sm text-[#6d756f]">{latest ? (grouped(latest).map(([name, count]) => `${name} × ${count}`).join(" · ") || "No detections") : "Upload a file to run image inference"}</p></div><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><Info label="Confidence" value={latest?.confidence ? `${Math.round(latest.confidence * 100)}%` : "—"}/><Info label="Animal count" value={String(latest?.animal_count ?? "—")}/><Info label="Location" value={latest?.location ?? "—"}/><Info label="Status" value={latest?.status ?? "—"}/></div></aside></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-[#d8ddd7] bg-[#fffdf8]"><div className="flex items-center justify-between p-6"><div><h2 className="font-semibold">Recent uploads</h2><p className="mt-1 text-sm text-[#6d756f]">Recently processed wildlife image detections.</p></div><span className="rounded-full ui-image-frame px-3 py-1 text-xs font-semibold text-[#2d7c78]">{rows.length} records</span></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-y border-[#e1e6e1] bg-[#eef3ee] text-xs uppercase tracking-wide text-[#7b8b81]"><tr><th className="px-6 py-4">Species</th><th className="px-6 py-4">Animals</th><th className="px-6 py-4">Confidence</th><th className="px-6 py-4">Location</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-[#e9efea]">{rows.map(row => <tr key={row.id}><td className="px-6 py-4"><p className="font-semibold">{grouped(row).map(([name, count]) => `${name} × ${count}`).join(" · ") || row.species?.common_name || "Unidentified"}</p><p className="text-xs italic text-[#839087]">{row.species?.scientific_name}</p></td><td className="px-6 py-4 font-semibold">{row.animal_count ?? "—"}</td><td className="px-6 py-4 font-semibold text-[#2d7c78]">{row.confidence ? `${Math.round(row.confidence * 100)}%` : "—"}</td><td className="px-6 py-4 text-sm"><span className="flex items-center gap-1"><MapPin size={13}/>{row.location ?? "—"}</span></td><td className="px-6 py-4"><span className="rounded-full bg-[#e3efec] px-2.5 py-1 text-xs font-semibold text-[#2d7c78]">{row.status}</span></td></tr>)}</tbody></table></div></section>
  </div></DashboardShell>;
}
function Info({label, value}: {label: string; value: string}) { return <div className="rounded-xl bg-[#eef4ef] p-3"><p className="text-xs text-[#6d756f]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
