"use client";

import { FormEvent, useEffect, useState } from "react";
import { Download, FileText, Plus, Trash2, X } from "lucide-react";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";
import { API_URL } from "@/lib/api";
import { createReport, deleteReport, generateReport, getReports, type Report } from "@/lib/api";
import { getSession } from "@/lib/auth-session";
import { Button } from "@/components/ui/button";
import { DataCard } from "@/components/shared/DataCard";
import { PageContainer } from "@/components/shared/PageContainer";
import { PageHeader } from "@/components/shared/Pageheader";

export function ReportsPage() { const [reports, setReports] = useState<Report[]>([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<number | null>(null); const load = async () => { const token = getSession()?.token; if (!token) return; try { setReports(await getReports(token)); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load reports."); } }; useEffect(() => { load(); }, []);
  const generate = async (id: number) => { const token = getSession()?.token; if (!token) return; try { setBusy(id); await generateReport(id, token); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to generate report."); } finally { setBusy(null); } };
  const download = async (report: Report) => { const token = getSession()?.token; if (!token) return; try { setBusy(report.id); const response = await fetch(`${API_URL}/reports/${report.id}/download`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Generate this report before downloading it."); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = `${report.name}.csv`; link.click(); URL.revokeObjectURL(url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to download report."); } finally { setBusy(null); } };
  const remove = async (report: Report) => { if (!confirm(`Delete ${report.name}?`)) return; const token = getSession()?.token; if (!token) return; try { await deleteReport(report.id, token); load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete report."); } };
  return <DashboardShell><PageContainer><PageHeader breadcrumb="Dashboard / Reports" title="Research reports" description="Generate and download reports from your live database."><Button onClick={() => setShowForm(true)}><Plus size={16} />Generate report</Button></PageHeader><section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="All reports" value={reports.length} /><Metric label="Generated" value={reports.filter(item => item.status === "Generated").length} /><Metric label="Drafts" value={reports.filter(item => item.status === "Draft").length} /></section><DataCard className="mt-6 overflow-hidden"><div className="p-6"><h2 className="font-semibold">Report history</h2><p className="mt-1 text-sm text-[#6d756f]">Create a report, generate its current CSV file, then download it.</p>{error && <p className="mt-3 text-sm text-[#bd5656]">{error}</p>}</div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead className="border-y border-[#e1e6e1] bg-[#eef3ee] text-xs uppercase tracking-wide text-[#7b8b81]"><tr>{["Report name", "Category", "Created", "Status", "Actions"].map(label => <th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-[#e9efea]">{reports.length ? reports.map(report => <tr key={report.id}><td className="px-5 py-4 font-semibold">{report.name}</td><td className="px-5 py-4 text-sm capitalize">{report.report_type}</td><td className="px-5 py-4 text-sm text-[#6d756f]">{new Date(report.created_at).toLocaleString()}</td><td className="px-5 py-4"><span className="rounded-full ui-image-frame px-2.5 py-1 text-xs font-semibold text-[#2d7c78]">{report.status}</span></td><td className="px-5 py-4"><div className="flex gap-2"><Button className="px-3 py-2 text-xs" onClick={() => generate(report.id)} disabled={busy === report.id}>{busy === report.id ? "Working…" : "Generate"}</Button><Button variant="secondary" className="px-3 py-2 text-xs" onClick={() => download(report)} disabled={busy === report.id || !report.file_path}><Download size={14} />Download</Button><button onClick={() => remove(report)} aria-label="Delete report" className="rounded-lg p-2 text-[#a94343] hover:bg-[#fff2f2]"><Trash2 size={16} /></button></div></td></tr>) : <tr><td colSpan={5} className="px-5 py-10 text-center text-sm text-[#6d756f]">No reports yet.</td></tr>}</tbody></table></div></DataCard>{showForm && <ReportForm close={() => setShowForm(false)} saved={() => { setShowForm(false); load(); }} />}</PageContainer></DashboardShell>; }
function Metric({ label, value }: { label: string; value: number }) { return <DataCard className="p-5"><FileText size={19} className="text-[#2d7c78]" /><p className="mt-5 text-sm text-[#6d756f]">{label}</p><p className="mt-1 text-3xl font-extrabold ui-page-title">{value}</p></DataCard>; }
function ReportForm({ close, saved }: { close: () => void; saved: () => void }) { const [name, setName] = useState(""); const [reportType, setReportType] = useState("population"); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); const token = getSession()?.token; if (!token) return; try { setBusy(true); await createReport({ name, report_type: reportType }, token); saved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create report."); } finally { setBusy(false); } }; return <div className="fixed inset-0 z-40 grid place-items-center bg-[#263746]/30 p-5"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-[#fffdf8] p-7 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2d7c78]">Database export</p><h2 className="mt-2 text-xl font-bold">Create report</h2></div><button type="button" onClick={close} aria-label="Close form"><X size={18} /></button></div><label className="mt-6 block text-sm font-medium">Report name<input required value={name} onChange={event => setName(event.target.value)} placeholder="August population summary" className="mt-1.5 w-full rounded-xl border border-[#d8ddd7] px-3 py-2.5 text-sm" /></label><label className="mt-4 block text-sm font-medium">Category<select value={reportType} onChange={event => setReportType(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#d8ddd7] px-3 py-2.5 text-sm"><option value="population">Population</option><option value="detection">Detection</option><option value="species">Species</option></select></label>{error && <p className="mt-3 text-sm text-[#bd5656]">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Creating…" : "Create report"}</Button></div></form></div>; }
