"""initial neon schema

Revision ID: 9745feb0644e
Revises: 
Create Date: 2026-08-15 23:12:58.362442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9745feb0644e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'recipient',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.add_column('detections', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('detections', 'species_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('detections', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('detections', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('detections', 'bounding_box',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_detection_source_created', 'detections', ['source_type', 'created_at'], unique=False)
    op.create_index('idx_detection_species_created', 'detections', ['species_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_detections_created_at'), 'detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_detections_source_type'), 'detections', ['source_type'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reports', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.add_column('surveys', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('surveys', 'survey_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('surveys', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.alter_column('surveys', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('surveys', 'survey_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('surveys', 'created_at')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reports', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index(op.f('ix_detections_source_type'), table_name='detections')
    op.drop_index(op.f('ix_detections_created_at'), table_name='detections')
    op.drop_index('idx_detection_species_created', table_name='detections')
    op.drop_index('idx_detection_source_created', table_name='detections')
    op.alter_column('detections', 'bounding_box',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('detections', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detections', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('detections', 'species_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('detections', 'created_at')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.alter_column('alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'recipient',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('alerts', 'created_at')
    # ### end Alembic commands ###
